### ISSUE TITLE
"Close" button is not styled correctly

### ISSUE THREAD

**Issue by dominikbullo** [remastr/django-unfold#20]
When you disable change permission in admin, "Close" button is not correctly styled. I used this command:
```
def has_change_permission(self, request, obj=None):
    return False
```

![5c07fd48-38b3-4d4b-a213-574e41812014](https://user-images.githubusercontent.com/24371558/198970937-e5086a6d-01cd-44a4-b66f-cc7bc042d1cf.png)

**Comment by lukasvinclav** [comment]
Thanks. Fixed https://github.com/remastr/django-unfold/commit/a3e8c0440b7c45657f0daf856fc2c7d159500198
