### ISSUE TITLE
Summernote fields are not displayed correctly

### ISSUE THREAD

**Issue by dominikbullo** [remastr/django-unfold#22]
When you disable change permission in admin via this command:
```
def has_change_permission(self, request, obj=None):
    return False
```
Summernote fields are displayed with HTML tags and without summernote widget/form.

![95dac518-6b36-47ae-8112-9303ae49cbb0](https://user-images.githubusercontent.com/24371558/198974090-32a144c6-9719-469d-8cab-57f581911c45.png)

**Comment by lukasvinclav** [comment]
To me this seems as expected behavior. How exactly these fields are displayed in native admin?

**Comment by dominikbullo** [comment]
IT would be nice if It allow WYSIWYG to display the content like this:
![image](https://user-images.githubusercontent.com/24371558/202254565-9ab2bb4a-8400-4adb-abdb-ba2c6778df02.png)

Or at least respect HTML tags and show generated HTML without escaping

**Comment by lukasvinclav** [comment]
Thank you very much for issue. In one of our latest updates we introduced WYSIWYG into Unfold so from now it is possible to use unfold.contrib.forms.widgets.WysiwygWidget which is going to be properly styled with dark mode support.

Regarding the first issue with text formatting, it is possible to use `preprocess_fields` property in `ModelAdmin` to fix the formatting. All necessary documentation is in README.md

**Comment by Prajwalkamde** [comment]
Hi, @dominikbullo which editor are you using?
