### ISSUE TITLE
Breadcrumb don't have a valid link

### ISSUE THREAD

**Issue by jfajardo** [remastr/django-unfold#25]
When I go to edit or create an item, the breadcrumb doesn't work properly, the link doesn't convert to a valid URL
https://user-images.githubusercontent.com/4583818/202024165-e2fb2355-7892-4438-8238-04160e63b422.mov

**Comment by lukasvinclav** [comment]
Hi, thanks for feedback. Where exactly should this breadcrumb item point at?

**Comment by jfajardo** [comment]
Hi @lukasvinclav this breadcrumb shall have a valid link, it doesn't convert the URL **admin:pos_product_changelist** and doesn't show the app_label breadcrumb home/product/product_1 , the app_label is missed home/**app_label**/product/product_1

**Comment by lukasvinclav** [comment]
Thanks for explanation. It is fixed here https://github.com/remastr/django-unfold/commit/e8b788d175179913413df576e0cc3b338a2568fe
