### ISSUE TITLE
Cursor moved in search field

### ISSUE THREAD

**Issue by mjmare** [remastr/django-unfold#31]
A tiny usability issue: when one adds a search field everything works as expected. However when executing the search and the page gets refreshed the cursor is moved to the beginning of the target text in the search field. 
So when one wants to edit or clear the target text one has to manually move the cursor to the end of the target text. 

Additionally, a button to clear the search box would be nice. 

(Using Safari)

**Comment by lukasvinclav** [comment]
Hi, good idea with cursor at the end but we see some limitations. When you want to put a cursor at the end of the input on autofocus, you have to use onFocus attribute on input element. So far so good, it works on first load, but what if you loose the focus on this element and then you click with your mouse in the middle of the written text (new focus)? Your cursor will be moved back at the end. Here you have an example what I'm thinking about https://jsfiddle.net/6jx9ufr1/ But maybe there is some clean solution which we are not aware.

Regarding the reset button for search element, that area with search input, actions, counter with selected rows and filters is pretty crowded. It would require some layout changes or some nice transition. Again, we are open to see some ideas how this problem can be solved.

**Comment by mjmare** [comment]
The example does not work on Safari, if the intent is to have the control have focus on page load. Nor does it move the cursor to the end when tapping in the middle of the text. I'm testing this on an iPad ATM. But I may misunderstand your intention.

**Comment by lukasvinclav** [comment]
From UX perspective, this problem requires more attention. From my perspective, this issue can be closed.
