### ISSUE TITLE
Doc request: give example of action

### ISSUE THREAD

**Issue by mjmare** [remastr/django-unfold#32]
It would be helpful (for beginners like me) to see a code example of an action. Esp because the action behaves differently from the standard Django admin actions (which are also not documented extensively).

I had trouble creating a detail page action. It was not clear what to return from the action. This now works, but now I'm trying to find out how to integrate the view with the Unfold templates. IOW what templates to extend.
 
 TIA!

**Comment by ardu1na** [comment]
+=1

**Comment by lukasvinclav** [comment]
Would you mind to elaborate little bit more? We have some basic integration here https://github.com/remastr/django-unfold#actions but I'm not sure which part is making problems to you.

**Comment by mjmare** [comment]
Hi Lukas
Currently the docs only state the bare minimum and presume knowledge of the regular Django Admin Actions. 
For less experienced people a more extensive example would be useful.
In particular, I was able to get the actions working (I already knew about the standard action), but I was not successful in creating a view called by an action that uses the Unfold UI styling. 
Now that I'm writing this, maybe what Im asking for is some example app that exercises all Unfold extras. 

TIA Marcel
