### ISSUE TITLE
how to pass extra context in change_list?

### ISSUE THREAD

**Issue by ardu1na** [remastr/django-unfold#33]
(im very new to django and programming and i'been a week trying to figure out how to do it, but i cant)

i want to display the result of the sum of all fields in change_list view 

there is a way to pass the extra context ?

thanks

**Comment by anefta** [comment]
Something like that you mean? https://books.agiliq.com/projects/django-admin-cookbook/en/latest/calculated_fields.html

**Comment by ardu1na** [comment]
yes but it's not the sum of all fileds into a new column . is the sum of the fileds of all rows passed as context in the template.

yesterday i try to do it with [ this library](https://pypi.org/project/django-with-extra-context-admin/) and could add the sum of all the instances of the model into the template change_list , Works with regular django (without unfold) 

also import-export doesnt work here (but this is another issue)

**Comment by lukasvinclav** [comment]
Hi, try to override changelist_view method and add additional variables through extra_context.

https://github.com/remastr/django-unfold/blob/main/src/unfold/admin.py#L421
