### ISSUE TITLE
Dark mode - actions_detail styling

### ISSUE THREAD

**Issue by HenrichHanusovsky** [remastr/django-unfold#34]
When using dark mode, actions_detail are not styled properly in detail. It remains with light mode design.

![image](https://user-images.githubusercontent.com/27486567/207052013-d98733f0-2e03-4a41-ab89-4d0769ed2829.png)

**Comment by lukasvinclav** [comment]
Thanks, fixed. https://github.com/remastr/django-unfold/commit/388f2fda1fcc78555ed2757e00603acc36631589
