### ISSUE TITLE
Fieldsets dont work

### ISSUE THREAD

**Issue by Doliwa79** [remastr/django-unfold#52]
How to add two fields in one row. Fieldsets dont work.
I use the standard django method
example code
fieldsets = (
('Category', {
'fields': (('title', 'description', 'file',), 'flag') }),
('Answer Option', {'fields': ('datacreated', 'datamodified',)}),
)

**Comment by lukasvinclav** [comment]
Do you want to display them side by side? Such a layout is not supported.
